databases:
  - name: empty-plates
    user: admin
    plan: free
    region: oregon

services:
  - type: web
    name: empty-plates
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: empty-plates
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false